apiVersion: v1
kind: Service
metadata:
  name: cardgame-master-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    role: app-master
